import type { NextPage } from "next";
import Head from "next/head";
import Backdrop from "../components/Backdrop";
import Navbar from "../components/Navbar";
import SideDrawer from "../components/SideDrawer";
import { useState } from "react";

// const Home: NextPage = () => {

//   const [isSideDrawer, setIsSideDrawer] = useState(false)

//   const toggleMenu = () => {
//       if(isSideDrawer) {
//         setIsSideDrawer(false)
//         return
//       }else{
//         setIsSideDrawer(true)
//       }
//   }

//   console.log(`isSideDrawer: ${isSideDrawer}`)

//   return (
//     <div>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <Navbar clickHandler={() => toggleMenu}/>
//       <SideDrawer clickHandler={() => toggleMenu} isOpen={isSideDrawer}/>
//       <Backdrop clickHandler={() => toggleMenu} isOpen={isSideDrawer}/>

//       {/* Sneaker Company

//       Fall Limited Edition Sneakers

//       These low-profile sneakers are your perfect casual wear companion. Featuring a
//       durable rubber outer sole, they’ll withstand everything the weather can offer.

//       $125.00
//       50%
//       $250.00

//       0
//       Add to cart */}

//     </div>
//   )

// }

// export default Home

import React, { Component } from "react";

interface State{
  isSideDrawer: boolean
}

interface Props{
}



export class Index extends Component<Props, State> {
  state = { isSideDrawer: false };

  toggleMenu = () => {
    this.setState((prevState) => {
      return { isSideDrawer: !prevState.isSideDrawer };
    });
  };

  render() {
    console.log(`isDrawerOpen: ${this.state.isSideDrawer}`);
    return (
      <div>
        <Navbar clickHandler={this.toggleMenu} />
        <SideDrawer clickHandler={this.toggleMenu} isOpen={this.state.isSideDrawer} />
        <Backdrop clickHandler={this.toggleMenu} isOpen={this.state.isSideDrawer} />
      </div>
    );
  }
}

export default Index;
